const images = {
  city: require("../assets/city.jpg"),
  kat: require("../assets/kat.png"),
  logo: require("../assets/formidable-logo.svg"),
  markdown: require("../assets/markdown.png"),
  jackfruitbbq: require('../assets/pics/jackfruitbbq.jpg'),
  baconish: require('../assets/pics/baconish.jpg'),
  cauliflower: require('../assets/pics/cauliflower.jpg'),
  kalebfast: require('../assets/pics/kalebfast.jpg'),
  asian: require('../assets/pics/asian.jpg'),
  ip: require('../assets/pics/ip.jpg'),
  pantry: require('../assets/pics/pantry.jpg'),
  risotto: require('../assets/pics/risotto.jpg'),
  sting1: require('../assets/pics/sting1.jpg'),
  sting2: require('../assets/pics/sting2.jpg'),
  sting3: require('../assets/pics/sting3.jpg'),
  sting4: require('../assets/pics/sting4.jpg'),
  taos1: require('../assets/pics/taos.jpg'),
  taos2: require('../assets/pics/taos2.jpg'),
  taos3: require('../assets/pics/taos3.jpg'),
  taos4: require('../assets/pics/taos4.jpg'),
  taos5: require('../assets/pics/taos5.jpg'),
  taos6: require('../assets/pics/taos6.jpg'),
  taos7: require('../assets/pics/taos7.jpg'),
  taos8: require('../assets/pics/taos8.jpg'),
  sand1: require('../assets/pics/sand1.jpg'),
  sand2: require('../assets/pics/sand2.jpg'),
  sand3: require('../assets/pics/sand3.jpg'),
  sand4: require('../assets/pics/sand4.jpg'),
  mountains1: require('../assets/pics/mountain1.jpg'),
  mountains2: require('../assets/pics/mountain2.jpg'),
  mountains3: require('../assets/pics/mountain3.jpg'),
  mountains4: require('../assets/pics/mountains4.jpg'),
  mountains5: require('../assets/pics/mountains5.jpg'),
  mountains6: require('../assets/pics/mountains6.jpg'),
  mountains7: require('../assets/pics/mountains7.jpg'),
  mountains8: require('../assets/pics/mountains8.jpg'),
  fred: require('../assets/pics/fred.jpg')
};

export default images
